services:
  postgres:
    container_name: booking_database
    image: postgres:alpine
    environment:
      POSTGRES_DB: booking
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
